### ISSUE TITLE
how autoload viz?

### ISSUE THREAD

**Issue by lalo4ka** [JerryXie98/vue-tableau#2]
how autoload viz without click on nice button?

why click to button?  i think it should be load by default 

by the way, nice job! congrats.

**Comment by Codaxl** [comment]
@lalo4ka Did you figure out how to autoload?

**Comment by lalo4ka** [comment]
Yes, i follow this tutorial.
https://medium.com/@andre.devries/embedding-tableau-the-vuejs-way-653c629724a

Its very easy  to integrate the Tableau JavaScript API in VueJS :)

**Comment by JerryXie98** [comment]
The button was mainly used for testing, the component should autoload without clicking the button. Sorry for the confusion.
